# Generated by Django 5.0.7 on 2024-08-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_rename_image_product1_image1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product1',
        ),
    ]
